name: e_shopee
description: A new Flutter project.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.8.4
  cupertino_icons: ^1.0.5
  enum_to_string: ^2.0.1
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.7
  future_progress_dialog: ^0.2.1
  image_picker: ^1.0.1
  intl: ^0.18.1
  logger: ^1.4.0
  permission_handler: ^10.4.3
  # pinch_zoom_image_updated: ^0.2.6
  provider: ^6.0.5
  string_validator: ^1.0.0
  url_launcher: ^6.1.12
  flutter_tags: ^1.0.0-nullsafety.1
  swipedetector_nullsafety: ^2.0.0
  csv: ^5.0.2
  expandable_bottom_sheet: ^1.1.1+1
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.3
  just_the_tooltip: ^0.0.12
  flutter_html: ^3.0.0-beta.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon_with_bg.png"

  flutter_lints: ^2.0.2


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/csv/


  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/font/JosefinSans-Regular.ttf
          weight: 400
        - asset: assets/font/JosefinSans-Medium.ttf
          weight: 500
        - asset: assets/font/JosefinSans-Bold.ttf
          weight: 700
        - asset: assets/font/JosefinSans-Black.ttf
          weight: 900
